### ISSUE TITLE
Lua 5.2 doesn't support bitwise operators

### ISSUE THREAD

**Issue by JakobCh** [Ocawesome101/open-kernel-2#3]
https://github.com/Ocawesome101/open-kernel-2/blob/4e899f8a4eeced532415c180ffaddfbbc3754f92/ksrc/modules/devfs.lua#L21

See: http://lua-users.org/wiki/BitwiseOperators
"Lua 5.3+ has native support for well-known bitwise operators."

This will cause the code to not run in OpenComputers
![image](https://user-images.githubusercontent.com/21036789/76708696-2ca32280-66f9-11ea-8575-e34f924e6ec2.png)

**Comment by Ocawesome101** [comment]
I am well aware that Open Kernel uses Lua 5.3’s bitwise operators. However,
it will run on the Lua 5.3 CPU architecture, accessed by
shift-right-clicking a CPU whilst in hand. It does have partial backwards
compatibility via `/lib/bit32.lua`.

**Comment by JakobCh** [comment]
Hmm that's weird Lua 5.3 should be the default architecture but it seams when I spawn CPUs in creative they start as 5.2.

You can use luacomp to generate different code depending on the lua version (luacomps lua version) like this:

`@[[if _VERSION == "Lua 5.2" then]]`
`print("Hey I'm Lua 5.2")`
`@[[else]]`
`print("Hey I'm Lua 5.3")`
`@[[end]]`

**Comment by Ocawesome101** [comment]
I’d check your OpenComputers config.

I will consider adding automatic version detection; thanks for the
suggestion :)
